### ISSUE TITLE
Skip button language

### ISSUE THREAD

**Issue by gouyelliot** [Cleveroad/slidingtutorial-android#34]
Hello there,

I actually can't find a way to custom/remove the "Skip" button, like changing the language according to my app.
Any update comming soon ?

EDIT:
Appear to be really easy finally, juste override onViewCreated in my TutorialSupportFragment

``` java
@Override
public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    View skipButton = view.findViewById(R.id.tvSkip);
    skipButton.setVisibility(View.INVISIBLE);
}
```

Elliot.

**Comment by Iojjj** [comment]
Hi @gouy-elliot,

you can also use a getter method called [getSkipButton](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialImpl.java#L138-L140). It will return you a reference to the skip button view. Because skip button is a regular `TextView` you can cast it to `TextView` and set your localized text.

One more way to localize `Skip` text is to create a sting resource with id `st_skip` and translate it to different languages. When your app being compiled, all resources will be merged and your `st_skip` resource will override library's one.

If this answers your question, please close the issue.
