### ISSUE TITLE
Add more than 3 PageFragements

### ISSUE THREAD

**Issue by sergiofalves** [Cleveroad/slidingtutorial-android#6]
Hi, we want to add more than 3 page fragments to your sliding, but after that, when the slider starts, it doesn't start on the first viewpager.
How can it be solved?

Thank you,

Sérgio

**Comment by Iojjj** [comment]
Hi there.

Thanks for your feedback. Is this a problem with infinite scroll? If so the problem is setting current item index [here (line 77)](https://github.com/Cleveroad/slidingtutorial-android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/PresentationPagerFragment.java#L77).

To fix this on your own pull latest version of library and replace those line with this ones:

``` Java
int pos = Integer.MAX_VALUE / 2;
pos -= pos % getPagesCount();
viewPager.setCurrentItem(pos);
```

The fix will be available in the next release, approximately on Monday, 22th.

**Comment by sergiofalves** [comment]
Thank you,  I will wait until next monday.

**Comment by Iojjj** [comment]
v.0.9.3 released
